### ISSUE TITLE
New Resource: Risk-based approach to deploying machine learning solutions in financial institutions

### ISSUE THREAD

**Issue by joefaith** [romanlutz/ResponsibleAI#1]
You might find this paper useful on managing the risks presented by ML solutions:
http://www.caspian.co.uk/rba/RBA.pdf

**Comment by romanlutz** [comment]
Hi @joefaith ! Thanks for the suggestion. I've briefly glanced at it and I'm not entirely sure how this fits in. Since you seem to be the author you can probably explain :-) The page collects mainly questionable use cases of AI, so that we can take them into account in the future when building (hopefully better) solutions.

**Comment by joefaith** [comment]
This paper identifies the ways we found that ML can go wrong when applied
to the problem of detecting money laundering (currently a very big problem
for financial institutions). And it collects together the ways we found to
mitigate those problems.

Machine Learning solutions are now ubiquitous in financial institutions
and, following the 2008 crash, regulators, such as the Federal Reserve
<https://www.federalreserve.gov/supervisionreg/srletters/sr1107.htm>, have
taken the lead in defining processes for managing the risks they present.
This is a huge area of concern for the responsible use of ML, though it is
often ignored by the academic community. It would be great if you could
help us make others more aware of this problem -- and the possible
solutions.

Thanks

Joe Faith

**Comment by romanlutz** [comment]
Thanks. I took a closer look at it now as well. The approach I've taken so far was to include pieces that describe problems with a certain approach, e.g. applied to this scenario that could be
"Thousands of people receive unjustified letters accusing them of money laundering due to bad ML model" (made-up headline)
I actually like the use case, but I don't see any case of people having tried this and failed at it. If people are all aware of the difficulty of the task and treat it with the appropriate amount of care then there's not a lot to report on this page, since the point is to provide people with questionable to outright unethical applications that they shouldn't repeat.

I hope this makes sense to you (?). If you do have such cases we can include links to them as well as your paper as a way to fix the problems. I couldn't find actual cases in the sources, though.

**Comment by joefaith** [comment]
Hey

In most cases the details of the failures of Anti Money Laundering systems
are highly confidential, since they can be exploited by criminals. The only
clues we get are from the fines that are levied against the institutions.
For example

HSBC fined $1.9bn in 2012 for Money laundering Mexican drug money; Iran,
Cuba,
Sudan, Libya, Burma sanctions breaches

Standard Chartered $1.1bn 2019 Terrorist money laundering and sanctions
breaches.

BNP Paribas $8.9bn 2014 Sanctions breaches, Cuba, Iran, Sudan

Each of these institutions had ML-based transaction monitoring systems in
place that failed.

And this is just the failures of ML in anti money laundering that I'm most
familiar with (and that we address in the paper). If you include trading
agents and credit rating applications then you could also include the 2010
flash crash, the collapse of LTCM, and much of the financial crisis of 2008!

It's interesting to me quite how little the academic and biomedical ML
communities learn from the financial industry's experience.

It would be great to start the dialogue.

J

**Comment by romanlutz** [comment]
That's fair. Thanks for providing this background for me! I'll see where I can add it.

**Comment by joefaith** [comment]
Thanks Roman

J
